language: r
dist: trusty
sudo: required
cache: packages

apt_packages:
  - libudunits2-dev

matrix: 
  include:
    - os: linux
       r: oldrel
    - os: linux
       r: release
       env: R_CODECOV=true

r_packages:
  - maps
  - scales
  - colorspace
  - raster

r_github_packages:
  - jimhester/covr

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos-dev netcdf-bin


compiler:
  - clang

after_success:
- if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

env:
   global:
     - R_LIBS="https://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: Y7ly6rxiG4EBAKKREFovZ1LPQp2ghrN7ThIfkMaQ1XCQLRV0D39a3Uuf1UigS6gpqrtaedXakbtZwG3CIhICILRRiQSZch3gGZUNMRkVrG/0wZDn7HwWOquTxPJEeH1AUlKYToxiI6rRqd/c3U4FwisKuIUHmvqDRA1NEtdiqJY=
