language: r
cache: packages
os: linux

jobs: 
  include:
    - r: oldrel
    - r: release
      env: R_CODECOV=true
    - r: devel
      env: _R_CHECK_LENGTH_1_LOGIC2_=TRUE

r_packages:
  - maps
  - scales
  - colorspace
  - raster
  - covr
  - protolite
  - sf
  
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - netcdf-bin
      - libprotobuf-dev
      - libprotoc-dev
      - protobuf-compiler

after_success:
- if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

env:
   global:
     - R_LIBS="https://cran.rstudio.com"
     - R_BUILD_ARGS="--no-build-vignettes --no-manual"
     - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
     - BOOTSTRAP_LATEX=""

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: Y7ly6rxiG4EBAKKREFovZ1LPQp2ghrN7ThIfkMaQ1XCQLRV0D39a3Uuf1UigS6gpqrtaedXakbtZwG3CIhICILRRiQSZch3gGZUNMRkVrG/0wZDn7HwWOquTxPJEeH1AUlKYToxiI6rRqd/c3U4FwisKuIUHmvqDRA1NEtdiqJY=
